In [3]:
import numpy as np  #Using an alias to use numpy as np

In [4]:
pricesA = np.array([100,200,300]) #matrix 1d
pricesB = np.array([400,500,600])
print(type(pricesA))
print(pricesA)
print(pricesA+pricesB) #matrix summation
print(pricesA*2) #matrix multiplication

<class 'numpy.ndarray'>
[100 200 300]
[500 700 900]
[200 400 600]


In [5]:
print(pricesA.shape) #shows the dimensions
print(pricesA.ndim) #shows the number of dimension
print(pricesA.dtype) #shows the data type
print(pricesA.size) #shows the number of elements

(3,)
1
int64
3


In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #creating 2d arrays
print(b)

print(b.shape)
print(b.size)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
2


In [7]:
print(np.zeros((3,3)))#make a zero matrix
print(np.ones((2,3), dtype='int')) #makes a matrix of ones in integer datatype
print(np.full((2,3),7.))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[7. 7. 7.]
 [7. 7. 7.]]


In [8]:
np.eye(4,dtype='int') #Identity Matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
print(np.random.rand(2,3)) #Take random number, where the number 0<n<1
print(np.random.randint(1,100,5)) #Takes lower and upperbound and generate random number inside that range
print(np.random.randint(1,100,(10,10))) #Matrix random generation using range

[[0.25341247 0.71931653 0.88162747]
 [0.45693033 0.12493023 0.57721547]]
[78 77 21 99 81]
[[65 59 80 43 58  9 81 61 54 26]
 [ 6 30 52 38  3 71 48 58 59 17]
 [58 92 64 35 71 65 15  9 92 77]
 [37  5  6 47 11 77 22 42 85 52]
 [16 76 50 93 80 58 26 93 43 32]
 [59 94  9 11 67 95 66 40 84 38]
 [45  6 17 89 85 19 63 25 56 98]
 [97 87 93 40  1 39 97 29 22 58]
 [72 14 45 17 20 64 43 29 65 26]
 [54 25 39 92 28 13 70 46 51 50]]


In [ ]:
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])

print(x*y)
print(np.dot(x,y)) #dot multiplication
print(x@y)         #dot multiplication shortcut

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
print(x.T)  # Transpose matrix

[[1 3]
 [2 4]]
