In [1]:
import numpy as np  #Using an alias to use numpy as np

In [3]:
pricesA = np.array([100,200,300]) #matrix 1d
pricesB = np.array([400,500,600])
print(type(pricesA))
print(pricesA)
print(pricesA+pricesB) #matrix summation
print(pricesA*2) #matrix multiplication

<class 'numpy.ndarray'>
[100 200 300]
[500 700 900]
[200 400 600]


In [4]:
print(pricesA.shape) #shows the dimensions
print(pricesA.ndim) #shows the number of dimension
print(pricesA.dtype) #shows the data type
print(pricesA.size) #shows the number of elements

(3,)
1
int64
3


In [5]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #creating 2d arrays
print(b)

print(b.shape)
print(b.size)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
2


In [7]:
print(np.zeros((3,3)))#make a zero matrix
print(np.ones((2,3), dtype='int')) #makes a matrix of ones in integer datatype
print(np.full((2,3),7.))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[7. 7. 7.]
 [7. 7. 7.]]


In [8]:
np.eye(4,dtype='int') #Identity Matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
print(np.random.rand(2,3)) #Take random number, where the number 0<n<1
print(np.random.randint(1,100,5)) #Takes lower and upperbound and generate random number inside that range
print(np.random.randint(1,100,(10,10))) #Matrix random generation using range

[[0.90239879 0.55790167 0.53283159]
 [0.02231555 0.45349428 0.77622927]]
[17 18  5 42 97]
[[99 31 11 91 69 34 69 91 53 96]
 [18 89 79 82 64 32 12 69 13 50]
 [44 88  5 84 67 68  9 22 75 44]
 [94  3 14 10 67 56 45 58  1 15]
 [40 45 47 74 81 64 32 69 44 23]
 [44 34 42 81 38 85 91 73 62 10]
 [24 38  9 78 14 28 54 73 68 51]
 [90 52 75 46 35 99  3 32 99 10]
 [42 98 95 10 86 73 38 13 14 34]
 [93 61 60 84 13 99 11 42 18 42]]
