In [ ]:
import numpy as np  #Using an alias to use numpy as np

In [ ]:
pricesA = np.array([100,200,300]) #matrix 1d
pricesB = np.array([400,500,600])
print(type(prices))
print(prices)
print(pricesA+pricesB) #matrix summation
print(prices*2) #matrix multiplication

<class 'numpy.ndarray'>
[100 200 300]
[500 700 900]
[200 400 600]


In [ ]:
print(pricesA.shape) #shows the dimensions
print(pricesA.ndim) #shows the number of dimension
print(pricesA.dtype) #shows the data type
print(pricesA.size) #shows the number of elements

(3,)
1
int64
3


In [22]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #creating 2d arrays
print(b)

print(b.shape)
print(b.size)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
2


In [29]:
print(np.zeros((3,3)))#make a zero matrix
print(np.ones((2,3), dtype='int')) #makes a matrix of ones in integer datatype
print(np.full((2,3),7.))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[7. 7. 7.]
 [7. 7. 7.]]


In [31]:
np.eye(4,dtype='int') #Identity Matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [52]:
print(np.random.rand(2,3)) #Take random number, where the number 0<n<1
print(np.random.randint(1,100,5)) #Takes lower and upperbound and generate random number inside that range
print(np.random.randint(1,100,(10,10))) #Matrix random generation using range

[[0.39412669 0.02095509 0.56979767]
 [0.82449221 0.27060474 0.43754406]]
[ 4 45 27 22 73]
[[92 26  5 66 26 52 54 87 14 69]
 [21 42  6 46 41 24 68 35 62 87]
 [58 82 39 91 17 70 10 76 59  5]
 [ 2 82 59 39 61 52 58 27  7 45]
 [34 96 23 98 19 71  3 62 43 18]
 [29 87 55 15  2  3 42 84 21 32]
 [93 59 45  5 10 36 91 25  2 45]
 [26 39 69 20 50 72 64 98 87 28]
 [80 60 42 28 69 49 85 55  6 14]
 [53 29  5 47 85 67 27 18  6 40]]
